name: cargo_connect_testing
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fluttertoast: ^8.2.4
  firebase_auth: ^4.16.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.14.0

  firebase_core: any
  google_maps_flutter: ^2.5.3
  flutter_polyline_points: ^2.0.0
  geolocator: ^11.0.0
  dio: ^5.4.1
  otp_text_field: ^1.1.3
  flutter_otp_text_field: ^1.1.3+2
  location: ^6.0.2
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  ios: true
  android: true
  image_path: "assets/logo-mini.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.19.4
  mockito: ^5.0.16
  build_runner: ^2.0.6

flutter:
  uses-material-design: true
  assets:
    - assets/pickup.png
    - assets/dropoff.png
    - assets/